#!/bin/bash

__HLOG="$ASAPSHELL_DIR/helpers/loging"
__HCOMMAND="$ASAPSHELL_DIR/helpers/command"
__HELPERFILES=($__HLOG $__HCOMMAND)

for i in "${__HELPERFILES[@]}"
do
  if [ -f "$i" ]; then
    source "$i"
  else
    error "$i does not exist."
  fi
done
