#!/bin/bash
# PHP Composer
alias com='composer'
alias com:v='composer -V'
alias com:init='composer init'
alias com:i='composer install'
alias com:up='composer update'
alias com:g:up='composer global update'
alias com:ug='composer upgrade'
alias com:re='composer require'
alias com:re:d='composer require --dev'
alias com:g:re='composer global require'
alias com:rm='composer remove'
alias com:rm:d='composer remove --dev'
alias com:g:s='composer global show'
