#!/bin/bash
# Git Flow
alias gf='git flow'
alias gf:v='git flow version'
alias gf:i='git flow init'
alias gf:f='git flow feature'
alias gf:fs='git flow feature start'
alias gf:ff='git flow feature finish'
alias gf:fp='git flow feature publish'
alias gf:fpull='git flow feature pull'
alias gf:ftrack='git flow feature track'
alias gf:h='git flow hotfix'
alias gf:hs='git flow hotfix start'
alias gf:hf='git flow hotfix finish'
alias gf:hp='git flow hotfix publish'
alias gf:r='git flow release'
alias gf:rs='git flow release start'
alias gf:rf='git flow release finish'
alias gf:rp='git flow release publish'
