#!/bin/bash
# Terraform
alias tf='terraform'
alias tf:fmt='terraform fmt'
alias tf:get='terraform get'
alias tf:i='terraform init'
alias tf:p='terraform plan'
alias tf:a='terraform apply'
alias tf:c='terraform console'
alias tf:d='terraform destroy'
alias tf:gr='terraform graph'
alias tf:login='terraform login'
alias tf:logout='terraform logout'
alias tf:o='terraform output'
alias tf:im='terraform import'
alias tf:pv='terraform providers'
alias tf:r='terraform refresh'
alias tf:s='terraform state'
alias tf:v='terraform validate'
alias tf:w='terraform workspace'
alias tf:w:n='terraform workspace new'
alias tf:w:l='terraform workspace list'
alias tf:w:s='terraform workspace select'
alias tf:w:d='terraform workspace delete'
alias tf:h='terraform -help'

# Function
