#!/bin/bash

# Initial environment
export ASAPSHELL_DIR=${ASAPSHELL_DIR:-$(asapshell_default_install_dir)}

# Source files variables
_SOURCE_FILE=$ASAPSHELL_DIR/src

# Helpers
source $ASAPSHELL_DIR/helpers/index.sh

# Config
source $ASAPSHELL_DIR/config/index.sh

# General aliases
source $_SOURCE_FILE/general/index.sh

### Get os name via uname ###
_myos=$(uname -s)

### add alias as per os using $_myos ###
case $_myos in
Linux) source $_SOURCE_FILE/linux/index.sh ;;
FreeBSD | OpenBSD) source $_SOURCE_FILE/bsd/index.sh ;;
Darwin) source $_SOURCE_FILE/darwin/index.sh ;;
*) ;;
esac

asapshell_default_install_dir() {
  [ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.asapshell" || printf %s "${XDG_CONFIG_HOME}/asapshell"
}
