#!/bin/bash
# PHP Composer
alias cm='composer'
alias cm:-h='composer --help'
alias cm:-v='composer -V'
alias cm:su='composer self-update'
alias cm:init='composer init'
alias cm:s='composer search'
alias cm:i='composer install'
alias cm:up='composer update'
alias cm:ug='composer upgrade'
alias cm:r='composer require'
alias cm:r:d='composer require --dev'
alias cm:rm='composer remove'
alias cm:rm:d='composer remove --dev'
alias cm:g:r='composer global require'
alias cm:g:u='composer global update'
alias cm:g:s='composer global show'
alias cm:cp='composer create-project'
alias cm:cs='composer create-script'
alias cm:cs:d='composer create-script --dev'
