#!/bin/bash
# NodeJs NPM #
alias node:-v='node -v'
alias npm:-v='npm -v'
alias npm:-h='npm --help'
alias npm:i='npm init'
alias npm:in='npm install'
alias npm:ud='npm update'
alias npm:dev='npm run dev'
alias npm:build='npm run build'
alias npm:build:s='npm run build-staging'
alias npm:build:p='npm run build-production'
alias npm:audit='npm audit fix'
alias npm:audit:f='npm audit fix --force'
alias npm:g:i='npm install --global'
alias npm:g:ui='npm uninstall --global'
alias npm:g:l='npm -g list --depth 0'
alias npm:g:o='npm -g outdated'
alias npm:g:u='npm -g update'
