#!/bin/bash

local __SYSTEM=$ASAPSHELL_DIR/os/linux/aliases/system
local __LINUXFILES=($__SYSTEM)

for i in "${__LINUXFILES[@]}"
do
  if [ -f "$i" ]; then
    source $i
  else
    error "$i does not exist."
  fi
done
